version: 1
disable_existing_loggers: true



formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  error:
    format: '%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ext://instance.config.INFO_LOG
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: ext://instance.config.ERROR_LOG
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: ext://instance.config.DEBUG_LOG
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  critical_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: CRITICAL
    formatter: standard
    filename: ext://instance.config.CRITICAL_LOG
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  warn_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: standard
    filename: ext://instance.config.WARN_LOG
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
  level: NOTSET
  handlers: [console]
  propogate: yes

loggers:
  chordify:
    level: INFO
    handlers: [console, warn_file_handler, error_file_handler, info_file_handler, critical_file_handler, debug_file_handler]
    propogate: no

  chordify_web:
    level: INFO
    handlers: [console, warn_file_handler, error_file_handler, info_file_handler, critical_file_handler, debug_file_handler]
    propogate: yes